### ISSUE TITLE
error getting Sound URL

### ISSUE THREAD

**Issue by JulienLevallois** [3llomi/iRecordView#12]
Hey, I got "error getting Sound URL" when I try to record with the demo version or with my version.

Why ? How can I get the soundfile?

Thanks

**Comment by 3llomi** [comment]
Hey @JulienLevallois ,
Are you testing against a Simulator or a Real Device? moreover can you try V0.1.3?

please note that this is a View Only Pod, which means you have to handle recording mechanism on your own. like start recording in `onStart` and stop it in `onFinish`
