### ISSUE TITLE
LongGestureRecognizer instead TapGesture?

### ISSUE THREAD

**Issue by dimidrollko** [3llomi/iRecordView#4]
Is it possible to override which type of gesture required for start recording? Providing this functionality will be helpful.

**Comment by 3llomi** [comment]
Hmm, can you tell me what is your use case? why would you need that?

**Comment by dimidrollko** [comment]
I want to merge functionality between sending text / voice with one button, for sending texts - just tap, and recording - long. But now it is implemented with two buttons, and everything is OK) 
thx

**Comment by 3llomi** [comment]
Well, it's already implmented. if you want to enable clicks you just have to call

```recordButton.listenForRecord = false```

by this you will disable the Gesture Recognizer so you can implement clicks using `@IBAction`
or 

```swift
recordButton.addTarget(self, action: #selector(recordButtonTapped), for: .touchUpInside)
```

**Comment by dimidrollko** [comment]
Ok. will check, thanks.
