### ISSUE TITLE
Crash on assigning AVAudioPlayer in version 13.1.3

### ISSUE THREAD

**Issue by himani-14** [3llomi/iRecordView#5]
line 35 in  AudioPlayer.swift
player = try AVAudioPlayer(contentsOf: url)

**Comment by raviseta07** [comment]
any solution for above issue.

**Comment by raviseta07** [comment]
@himani-14 : remove player = AVAudioPlayer() in live 21

**Comment by 3llomi** [comment]
i can't see this issue. anybody can reproduce it?
