### ISSUE TITLE
Getting Nil value from Bundle with corresponding identifier 

### ISSUE THREAD

**Issue by ramanocs1145** [3llomi/iRecordView#7]
Hi @3llomi ,

I'm getting nil value on Bundle from AudioPlayer.swift file which is on pod. So unable to play the recorded audio file as well as unable to fetch it.

`let bundle = Bundle(identifier: "org.cocoapods.iRecordView")`

```    
public func playAudioFile(soundType: AudioPlayerSounds) {
        let bundle = Bundle(identifier: "org.cocoapods.iRecordView")
        
        guard let url = bundle?.url(forResource: getPathByType(soundType: soundType), withExtension: "wav") else{
            print("error getting Sound URL")
            return
        }
        do {
            player = try AVAudioPlayer(contentsOf: url)
            player.play()

        } catch {
            print("could not play audio file!")
        }
    }
```

**Comment by Madhurr** [comment]
@ramanocs1145 

you are getting nil value on Bundle from AudioPlayer.swift file you are pointing to iRecorderView Example Bundle Identifier

// To provide your bundle identifier.
you can use

let bundle  = Bundle.main 

instead of  Bundle(identifier: "org.cocoapods.iRecordView")
