### ISSUE TITLE
holding strong reference

### ISSUE THREAD

**Issue by Ramandeep7193** [3llomi/iRecordView#8]
delegate property of record view class is strong it should be weak, I saw this issue was closed but delegate is still strong in latest version, please fix this issue asap

**Comment by 3llomi** [comment]
Oops, you are right. although it has been fixed in master branch, but not in Pod Trunk or V1.3 release.
i will try to fix it ASAP.

**Comment by 3llomi** [comment]
Fixed in 0.1.4
